import Head from "next/head";
import React from "react";
import Header from "./Header";
import PrimarySearchAppBar from "./Header";

type LayoutProps = {
  children: React.ReactNode;
};

const Layout = (props: LayoutProps): React.ReactNode => {
  return (
    <>
      <Head>
        <title>DrinkDazzel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/des-cocktails.png" />
      </Head>
      <body>
        <PrimarySearchAppBar />
        {props.children}
      </body>
    </>
  );
};

export default Layout;
